backend/urls.py
from django.urls import include, path

urlpatterns = [
    path("", include("weather.urls")),
]

handler404 = "weather.pages.views.handler404"


from weather.utils import set_cities_data

set_cities_data()

weather/urls.py
from django.urls import path
from .views import HomePageView, CityPageView, CityAutoCompleteView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("p/<str:name>/", CityPageView.as_view(), name="city"),
    path("api/autocomplete/", CityAutoCompleteView.as_view(), name="autocomplete"),
]

weather/models.py
from django.db import models

# Create your models here.

weather/forms.py
from django import forms


class WeatherForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        label=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter a Valid Place ...",
                "class": "form-control",
            }
        ),
    )

weather/pages/views.py
from django.shortcuts import render


def handler404(request, exception, *args, **kwargs):
    return render(request, "error.html", {}, status=404)

weather/views.py
import re
from django.views import View
from django.core.cache import cache
from django.shortcuts import render, redirect
from django.http import HttpRequest, JsonResponse

from .forms import WeatherForm
from .data import get_weather_data
from .utils import set_cities_data, get_clean_city_name


# Create your views here.


class HomePageView(View):
    context: dict = {}

    def get(self, request: HttpRequest, *args, **kwargs):
        form = WeatherForm()
        self.context["form"] = form
        return render(request, "index.html", context=self.context)

    def post(self, request: HttpRequest, *args, **kwargs):
        form = WeatherForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            return redirect(f"/p/{get_clean_city_name(name)}")
        self.context["form"] = form
        return render(request, "index.html", context=self.context)


class CityPageView(View):
    context: dict = {}

    def get(self, request: HttpRequest, *args, **kwargs):
        name = kwargs.get("name")
        data = get_weather_data(name)
        if data:
            self.context["data"] = data
            return render(request, "info.html", context=self.context)
        else:
            return render(request, "error.html", context=self.context)


class CityAutoCompleteView(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        query = request.GET.get("term", None)
        if query is None:
            return JsonResponse({}, safe=False)
        if cache.get("cities") is None:
            cities = set_cities_data()
            print("Lastest data from csv file")
        else:
            cities = cache.get("cities")
            print("Cached data")
        results = [city for city in cities if re.search(query, city, re.IGNORECASE)][:8]
        return JsonResponse(results, safe=False)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'css/bootstrap.html' %}
    {% include 'js/jquery.html' %}
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% include 'snippets/navbar.html' %}
    <div class="container">
      {% block body %}{% endblock %}
    </div>
    {% include 'js/bootstrap.html' %}
  </body>
</html>

templates/css/bootstrap.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous" />

templates/css/css.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous" />

templates/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Error 404</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700"
          rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'main.css' %}" />
  </head>
  <body>
    <div id="notfound">
      <div class="notfound">
        <div class="notfound-404">
          <h1>Oops!</h1>
          <h2>You have Entered a InValid Place</h2>
        </div>
        <a href="/">Go To Homepage</a>
      </div>
    </div>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Weather{% endblock %}
{% block body %}
  <link rel="stylesheet" type="text/css" href="{% static '/style.css' %}">
  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="container">
    <div class="text-center">
      <h2>Check the Weather of Your Place</h2>
      <hr>
    </div>
    <div class="text-center">
      <form method="POST">
        {% csrf_token %}
        <div class="text-center">{{ form }}</div>
        <br>
        <div class="text-center">
          <button type="submit" class="btn btn-success">Go...</button>
          <br>
          <br>
          <br>
          <br>
          <br>
          <br>
        </div>
      </form>
    </div>
  </div>
  <script>
    $(function() {
      $("#id_name").autocomplete({
        source: "{% url 'autocomplete' %}",
        minLength: 1,
      });
    });
  </script>
{% endblock %}

templates/info.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ data.city.capitalize }}{% endblock %}
{% block body %}
  <style type="text/css">
    body {
      background-image: url("{% static 'clouds.jpg' %}");
    }

    table {
      padding: 50px;
      font-weight: bold;
    }
  </style>
  <br>
  <br>
  <div class="container">
    <div class="text-center">
      <h1>Weather Data of {{ data.city.capitalize }}</h1>
    </div>
    <br>
    <hr>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Data</th>
          <th scope="col">Values</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">1</th>
          <td>Country Code</td>
          <td>{{ data.country_code }}</td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td>Latitude</td>
          <td>{{ data.latitude }} °</td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td>Longitude</td>
          <td>{{ data.longitude }} °</td>
        </tr>
        <tr>
          <th scope="row">4</th>
          <td>Temperature Minimum</td>
          <td>{{ data.temperature_min }} °C</td>
        </tr>
        <tr>
          <th scope="row">5</th>
          <td>Temperature</td>
          <td>{{ data.temperature }} °C</td>
        </tr>
        <tr>
          <th scope="row">6</th>
          <td>Temperature Maximum</td>
          <td>{{ data.temperature_max }} °C</td>
        </tr>
        <tr>
          <th scope="row">7</th>
          <td>How it Feels Like</td>
          <td>{{ data.temperature_feels_like }} °C</td>
        </tr>
        <tr>
          <th scope="row">8</th>
          <td>Forecast</td>
          <td>{{ data.main }}</td>
        </tr>
        <tr>
          <th scope="row">9</th>
          <td>Description</td>
          <td>{{ data.description }}</td>
        </tr>
        <tr>
          <th scope="row">10</th>
          <td>Pressure</td>
          <td>{{ data.pressure }} Hg</td>
        </tr>
        <tr>
          <th scope="row">11</th>
          <td>Humidity</td>
          <td>{{ data.humidity }} %</td>
        </tr>
        <tr>
          <th scope="row">12</th>
          <td>Wind Degree</td>
          <td>{{ data.wind_degree }} °</td>
        </tr>
        <tr>
          <th scope="row">13</th>
          <td>Wind Speed</td>
          <td>{{ data.wind_speed }} Kmph</td>
        </tr>
      </tbody>
    </table>
  </div>
{% endblock %}

templates/js/bootstrap.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

templates/js/jquery.html
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<link rel="stylesheet"
      href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

templates/js/js.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

templates/snippets/navbar.html
{% load static %}
<nav class="navbar bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Weather
      <img src="{% static 'weather.png' %}"
           alt=""
           width="40"
           height="40"
           class="d-inline-block align-text-top" />
    </a>
    <div class="d-flex">
      <p>
        <a href="https://arvind11.vercel.app"
           target="_blank"
           class="link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Arvind A</a>
      </p>
    </div>
  </div>
</nav>